name: Java Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file wha/pom.xml

      - name: Run Tests with Maven
        env:
          SPRING_PROFILES_ACTIVE: dev # Set the Spring profile to 'dev' for tests
        run: mvn test --file wha/pom.xml

      - name: Package and Create JAR
        run: mvn -B package
