name: Java Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests with Maven
        env:
          SPRING_PROFILES_ACTIVE: dev # Set the Spring profile to 'dev' for tests
        run: mvn test

      - name: Package and Create JAR
        run: mvn -B package

      - name: Upload Test Results
        if: always() # Always upload the results, even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports # Maven stores test reports here
